name: www.simtelligence.com
favicon: null
layout_spectrum: 0.9449671155307442
typography_spectrum: 0.5330612745601684
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6959519307129085
  lightness: 0.02571676205843687
  saturation: 0.012245198711752892
  rhythmicContrast: 0.6239067353308201
purpose: []
